In [28]:
from lazypredict.Supervised import LazyClassifier
import numpy as np
import pandas as pd
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.datasets import make_classification
from sklearn.ensemble import GradientBoostingClassifier

In [5]:
df = pd.read_csv(r'C:\Users\Anastasia\Documents\GitHub\ophthalmic_drugs\Analysis\irritation_MACCS.csv')
df

,exactmw,amw,lipinskiHBA,lipinskiHBD,NumRotatableBonds,NumHBD,NumHBA,NumHeavyAtoms,NumAtoms,NumHeteroatoms,...,chi1n,chi2n,chi3n,chi4n,hallKierAlpha,kappa1,kappa2,kappa3,Phi,Class
0,54.05,54.09,0.00,0.00,0.00,0.00,0.00,4.00,10.00,0.00,...,1.25,0.25,0.25,0.00,-0.44,3.56,2.56,1.56,2.28,1
1,56.06,56.11,0.00,0.00,1.00,0.00,0.00,4.00,12.00,0.00,...,1.52,0.29,0.29,0.00,-0.26,3.74,2.74,1.74,2.56,1
2,58.01,58.04,2.00,0.00,1.00,0.00,2.00,4.00,6.00,2.00,...,0.80,0.06,0.06,0.00,-0.66,3.34,2.34,1.34,1.95,1
3,58.04,58.08,1.00,0.00,1.00,0.00,1.00,4.00,10.00,1.00,...,1.35,0.17,0.17,0.00,-0.33,3.67,2.67,1.67,2.45,1
4,59.02,59.04,1.00,0.00,0.00,0.00,1.00,4.00,6.00,2.00,...,0.84,0.06,0.06,0.00,-0.58,3.42,2.42,1.42,2.07,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5215,780.43,780.95,14.00,6.00,7.00,6.00,14.00,55.00,119.00,14.00,...,20.93,15.82,15.82,12.86,-1.27,40.51,15.08,7.05,11.11,0
5216,780.43,780.95,14.00,6.00,7.00,6.00,14.00,55.00,119.00,14.00,...,20.94,15.95,15.95,12.76,-1.27,40.51,15.08,6.95,11.11,0
5217,788.85,789.10,11.00,6.00,9.00,6.00,8.00,32.00,54.00,14.00,...,8.93,4.37,4.37,2.56,-0.67,29.36,12.70,6.69,11.65,0
5218,790.87,791.12,11.00,7.00,11.00,7.00,8.00,32.00,56.00,14.00,...,9.25,4.11,4.11,2.55,-0.38,29.65,14.12,7.57,13.08,0
5219,794.45,794.98,14.00,5.00,8.00,5.00,14.00,56.00,122.00,14.00,...,21.33,16.19,16.19,13.10,-1.27,41.46,15.64,7.02,11.58,0

In [22]:
x = np.array(df.iloc[0:5220, 1:43])
y = np.array(df[['Class']])

In [12]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2, random_state=42)

In [13]:
reg = LazyClassifier(verbose=0, 
                    ignore_warnings=False, 
                    custom_metric=None)
models, predictions = reg.fit(xtrain, xtest, ytrain, ytest)
models

 14%|█▍        | 4/29 [00:02<00:13,  1.82it/s]

CategoricalNB model failed to execute
Negative values in data passed to CategoricalNB (input X)

 90%|████████▉ | 26/29 [00:08<00:00,  3.27it/s]

StackingClassifier model failed to execute
StackingClassifier.__init__() missing 1 required positional argument: 'estimators'

100%|██████████| 29/29 [00:10<00:00,  2.86it/s]

[LightGBM] [Info] Number of positive: 3103, number of negative: 1073
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001154 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 5628
[LightGBM] [Info] Number of data points in the train set: 4176, number of used features: 42
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.743056 -> initscore=1.061911
[LightGBM] [Info] Start training from score 1.061911

,Accuracy,Balanced Accuracy,ROC AUC,F1 Score,Time Taken
Model,,,,,
ExtraTreesClassifier,0.93,0.90,0.90,0.93,0.42
Perceptron,0.92,0.90,0.90,0.92,0.02
LGBMClassifier,0.93,0.90,0.90,0.93,0.15
XGBClassifier,0.93,0.89,0.89,0.93,1.38
LabelPropagation,0.93,0.89,0.89,0.93,0.67
LabelSpreading,0.93,0.89,0.89,0.93,0.81
SVC,0.93,0.89,0.89,0.93,0.26
BaggingClassifier,0.92,0.89,0.89,0.92,1.42
RandomForestClassifier,0.93,0.89,0.89,0.93,2.11
AdaBoostClassifier,0.92,0.89,0.89,0.92,1.08
KNeighborsClassifier,0.93,0.89,0.89,0.92,0.17
LinearSVC,0.91,0.86,0.86,0.91,0.25
CalibratedClassifierCV,0.91,0.86,0.86,0.91,0.18
LogisticRegression,0.91,0.86,0.86,0.91,0.05
PassiveAggressiveClassifier,0.90,0.86,0.86,0.90,0.03
SGDClassifier,0.90,0.85,0.85,0.90,0.04
QuadraticDiscriminantAnalysis,0.86,0.85,0.85,0.87,0.06
DecisionTreeClassifier,0.89,0.85,0.85,0.89,0.20
ExtraTreeClassifier,0.89,0.85,0.85,0.89,0.02
BernoulliNB,0.85,0.85,0.85,0.85,0.05
GaussianNB,0.88,0.84,0.84,0.88,0.02
NearestCentroid,0.89,0.84,0.84,0.88,0.02
NuSVC,0.89,0.83,0.83,0.89,0.61
LinearDiscriminantAnalysis,0.89,0.81,0.81,0.88,0.04
RidgeClassifier,0.89,0.81,0.81,0.88,0.02
RidgeClassifierCV,0.89,0.81,0.81,0.88,0.04
DummyClassifier,0.74,0.50,0.50,0.63,0.02

In [25]:
clf = ExtraTreesClassifier(n_estimators=100, random_state=0)
clf.fit(xtrain, ytrain)

ExtraTreesClassifier(random_state=0)

In [26]:
clf.score(xtest, ytest)

0.9262452107279694

In [27]:
clf.score(xtrain, ytrain)

1.0

In [29]:
clf = GradientBoostingClassifier(random_state=50)
clf.fit(xtrain, ytrain)

GradientBoostingClassifier(random_state=50)

In [30]:
clf.score(xtrain, ytrain)

0.9547413793103449

In [31]:
clf.score(xtest, ytest)

0.9252873563218391