In [1]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv(r'C:\Users\Anastasia\Documents\GitHub\ophthalmic_drugs\Data\melanin\fingerprints_melanin.csv')
df

,smiles,bit0,bit1,bit2,bit3,bit4,bit5,bit6,bit7,bit8,...,bit158,bit159,bit160,bit161,bit162,bit163,bit164,bit165,bit166,Melanin binding Fraction unbound (%)
0,CCN(CC)CCNC(=O)c1ccc(cc1)N.Cl,0,0,0,0,0,0,0,0,0,...,1,0,1,1,1,1,1,1,1,1.7
1,COCCNC(=O)CN1C2CCC1CC(C2)(c3cccnc3)O,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,0,38.7
2,CC1=NN=C(c2cc3c(cc2C1)OCO3)c4ccc(cc4)N,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,0,10.5
3,CC1C2Cc3ccc(cc3C1(CCN2CC=C)C)O,0,0,0,0,0,0,0,0,0,...,1,0,1,1,1,1,1,1,0,44.8
4,COc1ccc(cc1)c2coc3cc(ccc3c2=O)OC,0,0,0,0,0,0,0,0,0,...,0,1,1,0,1,1,1,1,0,5.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
775,c1ccc(cc1)c2cc(nc(n2)N)c3[nH]c4c(n3)cccn4,0,0,0,0,0,0,0,0,0,...,1,0,0,1,1,1,0,1,0,0.2
776,COc1ccc(cc1S(=O)(=O)N2CCc3c2cc(cc3)C(=O)Nc4nc(...,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,0,17.9
777,Cn1ccnc1c2c(cnc(n2)NCCOC)c3cccc(c3)OC,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,0,59.5
778,Cc1cnc(s1)Nc2c(nccn2)C3CCN(CC3)C,0,0,0,0,0,0,0,0,0,...,1,0,1,1,1,1,0,1,0,0.7
779,CCN1CCN(CC1)c2ncc(c(n2)c3ccoc3C)c4cc(no4)C,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,0,2.1

In [42]:
def f(row):
    global val
    if row['Melanin binding Fraction unbound (%)'] < 1:
        val = 0
    else:
        val = 1
    return val

In [43]:
df['Class'] = df.apply(f, axis=1)

In [44]:
df

,smiles,bit0,bit1,bit2,bit3,bit4,bit5,bit6,bit7,bit8,...,bit159,bit160,bit161,bit162,bit163,bit164,bit165,bit166,Melanin binding Fraction unbound (%),Class
0,CCN(CC)CCNC(=O)c1ccc(cc1)N.Cl,0,0,0,0,0,0,0,0,0,...,0,1,1,1,1,1,1,1,1.70,1
1,COCCNC(=O)CN1C2CCC1CC(C2)(c3cccnc3)O,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,0,38.70,1
2,CC1=NN=C(c2cc3c(cc2C1)OCO3)c4ccc(cc4)N,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,0,10.50,1
3,CC1C2Cc3ccc(cc3C1(CCN2CC=C)C)O,0,0,0,0,0,0,0,0,0,...,0,1,1,1,1,1,1,0,44.80,1
4,COc1ccc(cc1)c2coc3cc(ccc3c2=O)OC,0,0,0,0,0,0,0,0,0,...,1,1,0,1,1,1,1,0,5.50,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
775,c1ccc(cc1)c2cc(nc(n2)N)c3[nH]c4c(n3)cccn4,0,0,0,0,0,0,0,0,0,...,0,0,1,1,1,0,1,0,0.20,0
776,COc1ccc(cc1S(=O)(=O)N2CCc3c2cc(cc3)C(=O)Nc4nc(...,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,0,17.90,1
777,Cn1ccnc1c2c(cnc(n2)NCCOC)c3cccc(c3)OC,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,0,59.50,1
778,Cc1cnc(s1)Nc2c(nccn2)C3CCN(CC3)C,0,0,0,0,0,0,0,0,0,...,0,1,1,1,1,0,1,0,0.70,0
779,CCN1CCN(CC1)c2ncc(c(n2)c3ccoc3C)c4cc(no4)C,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,0,2.10,1

In [45]:
from lazypredict.Supervised import LazyClassifier

In [46]:
x = np.array(df.iloc[0:780, 1:168])
y = np.array(df[['Class']])

In [47]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2, random_state=42)

In [48]:
reg = LazyClassifier(verbose=0, 
                    ignore_warnings=False, 
                    custom_metric=None)
models, predictions = reg.fit(xtrain, xtest, ytrain, ytest)
models

 14%|█▍        | 4/29 [00:00<00:05,  4.95it/s]

CategoricalNB model failed to execute
Negative values in data passed to CategoricalNB (input X)

 55%|█████▌    | 16/29 [00:01<00:00, 14.08it/s]

NuSVC model failed to execute
specified nu is infeasible

100%|██████████| 29/29 [00:01<00:00, 14.74it/s]

StackingClassifier model failed to execute
StackingClassifier.__init__() missing 1 required positional argument: 'estimators'
[LightGBM] [Info] Number of positive: 491, number of negative: 133
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000564 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 372
[LightGBM] [Info] Number of data points in the train set: 624, number of used features: 124
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.786859 -> initscore=1.306095
[LightGBM] [Info] Start training from score 1.306095
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

,Accuracy,Balanced Accuracy,ROC AUC,F1 Score,Time Taken
Model,,,,,
LinearSVC,0.76,0.66,0.66,0.75,0.10
LogisticRegression,0.76,0.66,0.66,0.75,0.03
LinearDiscriminantAnalysis,0.76,0.65,0.65,0.75,0.09
PassiveAggressiveClassifier,0.72,0.65,0.65,0.73,0.02
LGBMClassifier,0.76,0.64,0.64,0.75,0.07
XGBClassifier,0.76,0.64,0.64,0.74,0.07
RidgeClassifier,0.76,0.64,0.64,0.75,0.02
BaggingClassifier,0.75,0.64,0.64,0.74,0.08
RidgeClassifierCV,0.77,0.63,0.63,0.75,0.09
QuadraticDiscriminantAnalysis,0.72,0.62,0.62,0.72,0.02
ExtraTreeClassifier,0.71,0.62,0.62,0.71,0.01
SGDClassifier,0.74,0.61,0.61,0.73,0.03
RandomForestClassifier,0.79,0.61,0.61,0.75,0.20
AdaBoostClassifier,0.75,0.61,0.61,0.73,0.11
NearestCentroid,0.59,0.61,0.61,0.62,0.02
BernoulliNB,0.65,0.60,0.60,0.66,0.02
Perceptron,0.73,0.58,0.58,0.71,0.01
ExtraTreesClassifier,0.75,0.58,0.58,0.71,0.20
SVC,0.76,0.55,0.55,0.69,0.04
KNeighborsClassifier,0.69,0.55,0.55,0.67,0.02
DecisionTreeClassifier,0.67,0.55,0.55,0.66,0.02
GaussianNB,0.34,0.54,0.54,0.28,0.01
CalibratedClassifierCV,0.74,0.52,0.52,0.66,0.57
DummyClassifier,0.74,0.50,0.50,0.63,0.01
LabelSpreading,0.29,0.50,0.50,0.20,0.05
LabelPropagation,0.29,0.50,0.50,0.20,0.03

In [49]:
from sklearn.ensemble import RandomForestClassifier	
clf = RandomForestClassifier(n_estimators=100, random_state=0)
clf.fit(xtrain, ytrain)

RandomForestClassifier(random_state=0)

In [50]:
clf.score(xtest, ytest)

0.782051282051282

In [51]:
clf.score(xtrain, ytrain)

0.9967948717948718

In [52]:
from sklearn.ensemble import GradientBoostingClassifier
clf = GradientBoostingClassifier(random_state=50)
clf.fit(xtrain, ytrain)

GradientBoostingClassifier(random_state=50)

In [53]:
clf.score(xtest, ytest)

0.7628205128205128

In [54]:
clf.score(xtrain, ytrain)

0.9391025641025641